"""Add column schedule

Revision ID: b303b9d8698a
Revises: 1335d84c8721
Create Date: 2025-07-10 16:13:50.918888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b303b9d8698a'
down_revision: Union[str, Sequence[str], None] = '1335d84c8721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_config', sa.Column('schedule_interval', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_config', 'schedule_interval')
    # ### end Alembic commands ###
